version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: sikta-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-sikta}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: sikta-api
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-sikta}?sslmode=disable
      PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    container_name: sikta-web
    environment:
      VITE_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./web/src:/app/src:z
      - ./web/public:/app/public:z
      - ./web/index.html:/app/index.html:z
      - ./web/vite.config.ts:/app/vite.config.ts:z
      - ./web/tailwind.config.ts:/app/tailwind.config.ts:z
      - ./web/postcss.config.js:/app/postcss.config.js:z
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data:
