// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chunk struct {
	ID               UUID               `json:"id"`
	DocumentID       UUID               `json:"document_id"`
	ChunkIndex       int32              `json:"chunk_index"`
	Content          string             `json:"content"`
	ChapterTitle     *string            `json:"chapter_title"`
	ChapterNumber    *int32             `json:"chapter_number"`
	PageStart        *int32             `json:"page_start"`
	PageEnd          *int32             `json:"page_end"`
	NarrativePosition int32             `json:"narrative_position"`
	WordCount        *int32             `json:"word_count"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
