// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: claims.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countClaimsBySource = `-- name: CountClaimsBySource :one
SELECT COUNT(*) FROM claims WHERE source_id = $1
`

func (q *Queries) CountClaimsBySource(ctx context.Context, sourceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClaimsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimsByStatusForSource = `-- name: CountClaimsByStatusForSource :many
SELECT review_status, COUNT(*) AS count
FROM claims
WHERE source_id = $1
GROUP BY review_status
`

type CountClaimsByStatusForSourceRow struct {
	ReviewStatus string `json:"review_status"`
	Count        int64  `json:"count"`
}

func (q *Queries) CountClaimsByStatusForSource(ctx context.Context, sourceID pgtype.UUID) ([]*CountClaimsByStatusForSourceRow, error) {
	rows, err := q.db.Query(ctx, countClaimsByStatusForSource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CountClaimsByStatusForSourceRow{}
	for rows.Next() {
		var i CountClaimsByStatusForSourceRow
		if err := rows.Scan(&i.ReviewStatus, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClaim = `-- name: CreateClaim :one
INSERT INTO claims (
    source_id, claim_type, title, description, event_type, date_text, date_start, date_end,
    date_precision, chronological_position, narrative_position, confidence,
    confidence_reason, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type
`

type CreateClaimParams struct {
	SourceID              pgtype.UUID `json:"source_id"`
	ClaimType             string      `json:"claim_type"`
	Title                 string      `json:"title"`
	Description           pgtype.Text `json:"description"`
	EventType             pgtype.Text `json:"event_type"`
	DateText              pgtype.Text `json:"date_text"`
	DateStart             pgtype.Date `json:"date_start"`
	DateEnd               pgtype.Date `json:"date_end"`
	DatePrecision         pgtype.Text `json:"date_precision"`
	ChronologicalPosition pgtype.Int4 `json:"chronological_position"`
	NarrativePosition     int32       `json:"narrative_position"`
	Confidence            float32     `json:"confidence"`
	ConfidenceReason      pgtype.Text `json:"confidence_reason"`
	Metadata              []byte      `json:"metadata"`
}

func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.SourceID,
		arg.ClaimType,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.DateText,
		arg.DateStart,
		arg.DateEnd,
		arg.DatePrecision,
		arg.ChronologicalPosition,
		arg.NarrativePosition,
		arg.Confidence,
		arg.ConfidenceReason,
		arg.Metadata,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}

const getClaim = `-- name: GetClaim :one
SELECT id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type FROM claims WHERE id = $1
`

func (q *Queries) GetClaim(ctx context.Context, id pgtype.UUID) (*Claim, error) {
	row := q.db.QueryRow(ctx, getClaim, id)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}

const listClaimsBySource = `-- name: ListClaimsBySource :many
SELECT id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type FROM claims WHERE source_id = $1 ORDER BY narrative_position
`

func (q *Queries) ListClaimsBySource(ctx context.Context, sourceID pgtype.UUID) ([]*Claim, error) {
	rows, err := q.db.Query(ctx, listClaimsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Claim{}
	for rows.Next() {
		var i Claim
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.Title,
			&i.Description,
			&i.EventType,
			&i.DateText,
			&i.DateStart,
			&i.DateEnd,
			&i.DatePrecision,
			&i.ChronologicalPosition,
			&i.NarrativePosition,
			&i.Confidence,
			&i.ConfidenceReason,
			&i.ReviewStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClaimType,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClaimChronologicalPosition = `-- name: UpdateClaimChronologicalPosition :one
UPDATE claims
SET chronological_position = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type
`

type UpdateClaimChronologicalPositionParams struct {
	ID                    pgtype.UUID `json:"id"`
	ChronologicalPosition pgtype.Int4 `json:"chronological_position"`
}

func (q *Queries) UpdateClaimChronologicalPosition(ctx context.Context, arg UpdateClaimChronologicalPositionParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimChronologicalPosition, arg.ID, arg.ChronologicalPosition)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}

const updateClaimConfidence = `-- name: UpdateClaimConfidence :one
UPDATE claims
SET confidence = $2, confidence_reason = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type
`

type UpdateClaimConfidenceParams struct {
	ID               pgtype.UUID `json:"id"`
	Confidence       float32     `json:"confidence"`
	ConfidenceReason pgtype.Text `json:"confidence_reason"`
}

func (q *Queries) UpdateClaimConfidence(ctx context.Context, arg UpdateClaimConfidenceParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimConfidence, arg.ID, arg.Confidence, arg.ConfidenceReason)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}

const updateClaimData = `-- name: UpdateClaimData :one
UPDATE claims
SET
    title = $2,
    description = $3,
    date_text = $4,
    event_type = $5,
    confidence = $6,
    review_status = 'edited',
    updated_at = NOW()
WHERE id = $1
RETURNING id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type
`

type UpdateClaimDataParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	DateText    pgtype.Text `json:"date_text"`
	EventType   pgtype.Text `json:"event_type"`
	Confidence  float32     `json:"confidence"`
}

func (q *Queries) UpdateClaimData(ctx context.Context, arg UpdateClaimDataParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimData,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DateText,
		arg.EventType,
		arg.Confidence,
	)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}

const updateClaimReviewStatus = `-- name: UpdateClaimReviewStatus :one
UPDATE claims
SET review_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, source_id, title, description, event_type, date_text, date_start, date_end, date_precision, chronological_position, narrative_position, confidence, confidence_reason, review_status, metadata, created_at, updated_at, claim_type
`

type UpdateClaimReviewStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	ReviewStatus string      `json:"review_status"`
}

func (q *Queries) UpdateClaimReviewStatus(ctx context.Context, arg UpdateClaimReviewStatusParams) (*Claim, error) {
	row := q.db.QueryRow(ctx, updateClaimReviewStatus, arg.ID, arg.ReviewStatus)
	var i Claim
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.DateText,
		&i.DateStart,
		&i.DateEnd,
		&i.DatePrecision,
		&i.ChronologicalPosition,
		&i.NarrativePosition,
		&i.Confidence,
		&i.ConfidenceReason,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClaimType,
	)
	return &i, err
}
