// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID           UUID               `json:"id"`
	Title        string             `json:"title"`
	Filename     string             `json:"filename"`
	FilePath     string             `json:"file_path"`
	FileType     string             `json:"file_type"`
	TotalPages   *int32             `json:"total_pages"`
	UploadStatus string             `json:"upload_status"`
	ErrorMessage *string            `json:"error_message"`
	IsDemo       bool               `json:"is_demo"`
	Metadata     *json.RawMessage   `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
