// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Event represents an extracted event.
type Event struct {
	ID                   UUID               `json:"id"`
	DocumentID           UUID               `json:"document_id"`
	Title                string             `json:"title"`
	Description          *string            `json:"description"`
	EventType            string             `json:"event_type"`
	DateText             *string            `json:"date_text"`
	DateStart            pgtype.Date        `json:"date_start"`
	DateEnd              pgtype.Date        `json:"date_end"`
	DatePrecision        *string            `json:"date_precision"`
	ChronologicalPosition *int32            `json:"chronological_position"`
	NarrativePosition    int32              `json:"narrative_position"`
	Confidence           float64            `json:"confidence"`
	ConfidenceReason     *string            `json:"confidence_reason"`
	ReviewStatus         string             `json:"review_status"`
	Metadata             pgtype.Map          `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Entity represents an extracted entity.
type Entity struct {
	ID                   UUID               `json:"id"`
	DocumentID           UUID               `json:"document_id"`
	Name                 string             `json:"name"`
	EntityType           string             `json:"entity_type"`
	Aliases              []string           `json:"aliases"`
	Description          *string            `json:"description"`
	FirstAppearanceChunk *int32             `json:"first_appearance_chunk"`
	LastAppearanceChunk  *int32             `json:"last_appearance_chunk"`
	Confidence           float64            `json:"confidence"`
	ReviewStatus         string             `json:"review_status"`
	Metadata             pgtype.Map          `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// Relationship represents a relationship between entities.
type Relationship struct {
	ID                UUID               `json:"id"`
	DocumentID        UUID               `json:"document_id"`
	EntityAID         UUID               `json:"entity_a_id"`
	EntityBID         UUID               `json:"entity_b_id"`
	RelationshipType  string             `json:"relationship_type"`
	Description       *string            `json:"description"`
	StartEventID      *UUID              `json:"start_event_id"`
	EndEventID        *UUID              `json:"end_event_id"`
	Confidence        float64            `json:"confidence"`
	ReviewStatus      string             `json:"review_status"`
	Metadata          pgtype.Map          `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// SourceReference represents a link to source text.
type SourceReference struct {
	ID           UUID               `json:"id"`
	ChunkID      UUID               `json:"chunk_id"`
	EventID      *UUID              `json:"event_id"`
	EntityID     *UUID              `json:"entity_id"`
	RelationshipID *UUID             `json:"relationship_id"`
	Excerpt      string             `json:"excerpt"`
	CharStart    *int32             `json:"char_start"`
	CharEnd      *int32             `json:"char_end"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// EventEntity represents an event-entity relationship.
type EventEntity struct {
	EventID   UUID    `json:"event_id"`
	EntityID  UUID    `json:"entity_id"`
	Role      *string `json:"role"`
}
