// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nodes.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNodesByType = `-- name: CountNodesByType :one
SELECT node_type, COUNT(*) as count
FROM nodes
GROUP BY node_type
ORDER BY count DESC
`

type CountNodesByTypeRow struct {
	NodeType string `json:"node_type"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountNodesByType(ctx context.Context) (*CountNodesByTypeRow, error) {
	row := q.db.QueryRow(ctx, countNodesByType)
	var i CountNodesByTypeRow
	err := row.Scan(&i.NodeType, &i.Count)
	return &i, err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (node_type, label, properties)
VALUES ($1, $2, $3)
RETURNING id, node_type, label, properties, created_at, updated_at
`

type CreateNodeParams struct {
	NodeType   string `json:"node_type"`
	Label      string `json:"label"`
	Properties []byte `json:"properties"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (*Node, error) {
	row := q.db.QueryRow(ctx, createNode, arg.NodeType, arg.Label, arg.Properties)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.Label,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes
WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getDocumentNodeByLegacySourceID = `-- name: GetDocumentNodeByLegacySourceID :one
SELECT id, node_type, label, properties, created_at, updated_at FROM nodes
WHERE node_type = 'document'
  AND properties->>'source_id' = $1::text
LIMIT 1
`

func (q *Queries) GetDocumentNodeByLegacySourceID(ctx context.Context, dollar_1 string) (*Node, error) {
	row := q.db.QueryRow(ctx, getDocumentNodeByLegacySourceID, dollar_1)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.Label,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getNode = `-- name: GetNode :one
SELECT id, node_type, label, properties, created_at, updated_at FROM nodes
WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id pgtype.UUID) (*Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.Label,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listNodes = `-- name: ListNodes :many
SELECT id, node_type, label, properties, created_at, updated_at FROM nodes
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListNodes(ctx context.Context, limit int32) ([]*Node, error) {
	rows, err := q.db.Query(ctx, listNodes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.NodeType,
			&i.Label,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesBySource = `-- name: ListNodesBySource :many
SELECT DISTINCT n.id, n.node_type, n.label, n.properties, n.created_at, n.updated_at
FROM nodes n
INNER JOIN provenance p ON p.target_type = 'node' AND p.target_id = n.id
WHERE p.source_id = $1
ORDER BY n.created_at DESC
`

// List all nodes that have provenance from a specific source
func (q *Queries) ListNodesBySource(ctx context.Context, sourceID pgtype.UUID) ([]*Node, error) {
	rows, err := q.db.Query(ctx, listNodesBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.NodeType,
			&i.Label,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByType = `-- name: ListNodesByType :many
SELECT id, node_type, label, properties, created_at, updated_at FROM nodes
WHERE node_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListNodesByTypeParams struct {
	NodeType string `json:"node_type"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) ListNodesByType(ctx context.Context, arg ListNodesByTypeParams) ([]*Node, error) {
	rows, err := q.db.Query(ctx, listNodesByType, arg.NodeType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.NodeType,
			&i.Label,
			&i.Properties,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes
SET label = $2,
    properties = $3
WHERE id = $1
RETURNING id, node_type, label, properties, created_at, updated_at
`

type UpdateNodeParams struct {
	ID         pgtype.UUID `json:"id"`
	Label      string      `json:"label"`
	Properties []byte      `json:"properties"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (*Node, error) {
	row := q.db.QueryRow(ctx, updateNode, arg.ID, arg.Label, arg.Properties)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.NodeType,
		&i.Label,
		&i.Properties,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
