// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (title, description)
VALUES ($1, $2)
RETURNING id, title, description, created_at, updated_at
`

type CreateProjectParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, title, description, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (*Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getProjectSources = `-- name: GetProjectSources :many
SELECT id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason, project_id FROM sources WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetProjectSources(ctx context.Context, projectID pgtype.UUID) ([]*Source, error) {
	rows, err := q.db.Query(ctx, getProjectSources, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FilePath,
			&i.FileType,
			&i.TotalPages,
			&i.UploadStatus,
			&i.ErrorMessage,
			&i.IsDemo,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceTrust,
			&i.TrustReason,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectStats = `-- name: GetProjectStats :one
SELECT
    COUNT(DISTINCT s.id) as doc_count,
    COALESCE(SUM(CASE WHEN n.id IS NOT NULL THEN 1 ELSE 0 END), 0)::bigint as node_count,
    COALESCE(SUM(CASE WHEN e.id IS NOT NULL THEN 1 ELSE 0 END), 0)::bigint as edge_count
FROM sources s
LEFT JOIN nodes n ON n.source_id = s.id
LEFT JOIN edges e ON e.source_id = s.id
WHERE s.project_id = $1
`

type GetProjectStatsRow struct {
	DocCount  int64 `json:"doc_count"`
	NodeCount int64 `json:"node_count"`
	EdgeCount int64 `json:"edge_count"`
}

func (q *Queries) GetProjectStats(ctx context.Context, projectID pgtype.UUID) (*GetProjectStatsRow, error) {
	row := q.db.QueryRow(ctx, getProjectStats, projectID)
	var i GetProjectStatsRow
	err := row.Scan(&i.DocCount, &i.NodeCount, &i.EdgeCount)
	return &i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, description, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]*Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSourceProject = `-- name: SetSourceProject :one
UPDATE sources
SET project_id = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason, project_id
`

type SetSourceProjectParams struct {
	ID        pgtype.UUID `json:"id"`
	ProjectID pgtype.UUID `json:"project_id"`
}

func (q *Queries) SetSourceProject(ctx context.Context, arg SetSourceProjectParams) (*Source, error) {
	row := q.db.QueryRow(ctx, setSourceProject, arg.ID, arg.ProjectID)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.FilePath,
		&i.FileType,
		&i.TotalPages,
		&i.UploadStatus,
		&i.ErrorMessage,
		&i.IsDemo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTrust,
		&i.TrustReason,
		&i.ProjectID,
	)
	return &i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET title = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (*Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Title, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
