// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationships.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRelationshipsBySource = `-- name: CountRelationshipsBySource :one
SELECT COUNT(*) FROM relationships WHERE source_id = $1
`

func (q *Queries) CountRelationshipsBySource(ctx context.Context, sourceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRelationshipsBySource, sourceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationships (
    source_id, entity_a_id, entity_b_id, relationship_type, description,
    start_claim_id, end_claim_id, confidence, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, source_id, entity_a_id, entity_b_id, relationship_type, description, start_claim_id, end_claim_id, confidence, review_status, metadata, created_at, updated_at
`

type CreateRelationshipParams struct {
	SourceID         pgtype.UUID `json:"source_id"`
	EntityAID        pgtype.UUID `json:"entity_a_id"`
	EntityBID        pgtype.UUID `json:"entity_b_id"`
	RelationshipType string      `json:"relationship_type"`
	Description      pgtype.Text `json:"description"`
	StartClaimID     pgtype.UUID `json:"start_claim_id"`
	EndClaimID       pgtype.UUID `json:"end_claim_id"`
	Confidence       float32     `json:"confidence"`
	Metadata         []byte      `json:"metadata"`
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (*Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.SourceID,
		arg.EntityAID,
		arg.EntityBID,
		arg.RelationshipType,
		arg.Description,
		arg.StartClaimID,
		arg.EndClaimID,
		arg.Confidence,
		arg.Metadata,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.EntityAID,
		&i.EntityBID,
		&i.RelationshipType,
		&i.Description,
		&i.StartClaimID,
		&i.EndClaimID,
		&i.Confidence,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRelationship = `-- name: GetRelationship :one
SELECT id, source_id, entity_a_id, entity_b_id, relationship_type, description, start_claim_id, end_claim_id, confidence, review_status, metadata, created_at, updated_at FROM relationships WHERE id = $1
`

func (q *Queries) GetRelationship(ctx context.Context, id pgtype.UUID) (*Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationship, id)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.EntityAID,
		&i.EntityBID,
		&i.RelationshipType,
		&i.Description,
		&i.StartClaimID,
		&i.EndClaimID,
		&i.Confidence,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRelationshipsByEntity = `-- name: ListRelationshipsByEntity :many
SELECT id, source_id, entity_a_id, entity_b_id, relationship_type, description, start_claim_id, end_claim_id, confidence, review_status, metadata, created_at, updated_at FROM relationships
WHERE entity_a_id = $1 OR entity_b_id = $1
`

func (q *Queries) ListRelationshipsByEntity(ctx context.Context, entityAID pgtype.UUID) ([]*Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsByEntity, entityAID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.EntityAID,
			&i.EntityBID,
			&i.RelationshipType,
			&i.Description,
			&i.StartClaimID,
			&i.EndClaimID,
			&i.Confidence,
			&i.ReviewStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsBySource = `-- name: ListRelationshipsBySource :many
SELECT id, source_id, entity_a_id, entity_b_id, relationship_type, description, start_claim_id, end_claim_id, confidence, review_status, metadata, created_at, updated_at FROM relationships WHERE source_id = $1
`

func (q *Queries) ListRelationshipsBySource(ctx context.Context, sourceID pgtype.UUID) ([]*Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Relationship{}
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.EntityAID,
			&i.EntityBID,
			&i.RelationshipType,
			&i.Description,
			&i.StartClaimID,
			&i.EndClaimID,
			&i.Confidence,
			&i.ReviewStatus,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationshipReviewStatus = `-- name: UpdateRelationshipReviewStatus :one
UPDATE relationships
SET review_status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, source_id, entity_a_id, entity_b_id, relationship_type, description, start_claim_id, end_claim_id, confidence, review_status, metadata, created_at, updated_at
`

type UpdateRelationshipReviewStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	ReviewStatus string      `json:"review_status"`
}

func (q *Queries) UpdateRelationshipReviewStatus(ctx context.Context, arg UpdateRelationshipReviewStatusParams) (*Relationship, error) {
	row := q.db.QueryRow(ctx, updateRelationshipReviewStatus, arg.ID, arg.ReviewStatus)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.EntityAID,
		&i.EntityBID,
		&i.RelationshipType,
		&i.Description,
		&i.StartClaimID,
		&i.EndClaimID,
		&i.Confidence,
		&i.ReviewStatus,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
