// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schema_version.sql

package database

import (
	"context"
)

const listSchemaVersions = `-- name: ListSchemaVersions :many
SELECT id, version, applied_at
FROM schema_versions
ORDER BY id
`

func (q *Queries) ListSchemaVersions(ctx context.Context) ([]*SchemaVersion, error) {
	rows, err := q.db.Query(ctx, listSchemaVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*SchemaVersion{}
	for rows.Next() {
		var i SchemaVersion
		if err := rows.Scan(&i.ID, &i.Version, &i.AppliedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
