// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sources.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSource = `-- name: CreateSource :one
INSERT INTO sources (title, filename, file_path, file_type, upload_status, is_demo)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason
`

type CreateSourceParams struct {
	Title        string `json:"title"`
	Filename     string `json:"filename"`
	FilePath     string `json:"file_path"`
	FileType     string `json:"file_type"`
	UploadStatus string `json:"upload_status"`
	IsDemo       bool   `json:"is_demo"`
}

func (q *Queries) CreateSource(ctx context.Context, arg CreateSourceParams) (*Source, error) {
	row := q.db.QueryRow(ctx, createSource,
		arg.Title,
		arg.Filename,
		arg.FilePath,
		arg.FileType,
		arg.UploadStatus,
		arg.IsDemo,
	)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.FilePath,
		&i.FileType,
		&i.TotalPages,
		&i.UploadStatus,
		&i.ErrorMessage,
		&i.IsDemo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTrust,
		&i.TrustReason,
	)
	return &i, err
}

const getSource = `-- name: GetSource :one
SELECT id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason FROM sources WHERE id = $1
`

func (q *Queries) GetSource(ctx context.Context, id pgtype.UUID) (*Source, error) {
	row := q.db.QueryRow(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.FilePath,
		&i.FileType,
		&i.TotalPages,
		&i.UploadStatus,
		&i.ErrorMessage,
		&i.IsDemo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTrust,
		&i.TrustReason,
	)
	return &i, err
}

const listSources = `-- name: ListSources :many
SELECT id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason FROM sources ORDER BY created_at DESC
`

func (q *Queries) ListSources(ctx context.Context) ([]*Source, error) {
	rows, err := q.db.Query(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Filename,
			&i.FilePath,
			&i.FileType,
			&i.TotalPages,
			&i.UploadStatus,
			&i.ErrorMessage,
			&i.IsDemo,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceTrust,
			&i.TrustReason,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSourceStatus = `-- name: UpdateSourceStatus :one
UPDATE sources
SET upload_status = $2,
    error_message = $3,
    updated_at    = NOW()
WHERE id = $1
RETURNING id, title, filename, file_path, file_type, total_pages, upload_status, error_message, is_demo, metadata, created_at, updated_at, source_trust, trust_reason
`

type UpdateSourceStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	UploadStatus string      `json:"upload_status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateSourceStatus(ctx context.Context, arg UpdateSourceStatusParams) (*Source, error) {
	row := q.db.QueryRow(ctx, updateSourceStatus, arg.ID, arg.UploadStatus, arg.ErrorMessage)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Filename,
		&i.FilePath,
		&i.FileType,
		&i.TotalPages,
		&i.UploadStatus,
		&i.ErrorMessage,
		&i.IsDemo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceTrust,
		&i.TrustReason,
	)
	return &i, err
}

const updateSourceTotalPages = `-- name: UpdateSourceTotalPages :exec
UPDATE sources
SET total_pages = $2,
    updated_at  = NOW()
WHERE id = $1
`

type UpdateSourceTotalPagesParams struct {
	ID         pgtype.UUID `json:"id"`
	TotalPages pgtype.Int4 `json:"total_pages"`
}

func (q *Queries) UpdateSourceTotalPages(ctx context.Context, arg UpdateSourceTotalPagesParams) error {
	_, err := q.db.Exec(ctx, updateSourceTotalPages, arg.ID, arg.TotalPages)
	return err
}
